[package]
name = "CordChan_Discord-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.5.*", features = ["full"] }
anyhow = "1.0.*"
serenity = "0.10.*"
ron = "0.7.*"